/**
 * The production RTT 2.X screener universe: real, verified NSE equities with
 * their Upstox instrument keys (ISIN-based, e.g. "NSE_EQ|INE066F01020"),
 * verified against the public Upstox NSE instrument master. This is the
 * combined, de-duplicated membership of the Nifty 100 and Nifty Midcap 150
 * indices (official NSE Indices constituent lists; Smallcap 250 was left out
 * to keep live-data load within realistic Upstox rate limits for the demo),
 * with each company's sector taken directly from NSE's own "Industry"
 * classification for that constituent -- not a hand-picked category.
 *
 * No prices, scores, or candles are stored here -- those are always fetched
 * live from Upstox and computed by the real RTT 2.X engine.
 */
export type UniverseStock = {
  symbol: string;
  companyName: string;
  sector: string;
  instrumentKey: string;
};

export const RTT2X_UNIVERSE: readonly UniverseStock[] = [
  { symbol: "360ONE", companyName: "360 ONE WAM Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE466L01038" },
  { symbol: "3MINDIA", companyName: "3M India Ltd", sector: "Diversified", instrumentKey: "NSE_EQ|INE470A01017" },
  { symbol: "ABB", companyName: "ABB India Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE117A01022" },
  { symbol: "ABBOTINDIA", companyName: "Abbott India Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE358A01014" },
  { symbol: "ABCAPITAL", companyName: "Aditya Birla Capital Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE674K01013" },
  { symbol: "ACC", companyName: "ACC Ltd", sector: "Construction Materials", instrumentKey: "NSE_EQ|INE012A01025" },
  { symbol: "ADANIENSOL", companyName: "Adani Energy Solutions Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE931S01010" },
  { symbol: "ADANIENT", companyName: "Adani Enterprises Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE423A01024" },
  { symbol: "ADANIGREEN", companyName: "Adani Green Energy Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE364U01010" },
  { symbol: "ADANIPORTS", companyName: "Adani Ports and Special Economic Zone Ltd", sector: "Services", instrumentKey: "NSE_EQ|INE742F01042" },
  { symbol: "ADANIPOWER", companyName: "Adani Power Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE814H01029" },
  { symbol: "AIAENG", companyName: "AIA Engineering Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE212H01026" },
  { symbol: "AIIL", companyName: "Authum Investment & Infrastructure Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE206F01022" },
  { symbol: "AJANTPHARM", companyName: "Ajanta Pharmaceuticals Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE031B01049" },
  { symbol: "ALKEM", companyName: "Alkem Laboratories Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE540L01014" },
  { symbol: "AMBUJACEM", companyName: "Ambuja Cements Ltd", sector: "Construction Materials", instrumentKey: "NSE_EQ|INE079A01024" },
  { symbol: "ANTHEM", companyName: "Anthem Biosciences Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE0CZ201020" },
  { symbol: "APARINDS", companyName: "Apar Industries Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE372A01015" },
  { symbol: "APLAPOLLO", companyName: "APL Apollo Tubes Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE702C01027" },
  { symbol: "APOLLOHOSP", companyName: "Apollo Hospitals Enterprise Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE437A01024" },
  { symbol: "APOLLOTYRE", companyName: "Apollo Tyres Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE438A01022" },
  { symbol: "ASHOKLEY", companyName: "Ashok Leyland Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE208A01029" },
  { symbol: "ASIANPAINT", companyName: "Asian Paints Ltd", sector: "Consumer Durables", instrumentKey: "NSE_EQ|INE021A01026" },
  { symbol: "ASTRAL", companyName: "Astral Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE006I01046" },
  { symbol: "ATGL", companyName: "Adani Total Gas Ltd", sector: "Oil Gas & Consumable Fuels", instrumentKey: "NSE_EQ|INE399L01023" },
  { symbol: "AUBANK", companyName: "AU Small Finance Bank Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE949L01017" },
  { symbol: "AUROPHARMA", companyName: "Aurobindo Pharma Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE406A01037" },
  { symbol: "AWL", companyName: "AWL Agri Business Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE699H01024" },
  { symbol: "AXISBANK", companyName: "Axis Bank Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE238A01034" },
  { symbol: "BAJAJ-AUTO", companyName: "Bajaj Auto Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE917I01010" },
  { symbol: "BAJAJFINSV", companyName: "Bajaj Finserv Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE918I01026" },
  { symbol: "BAJAJHFL", companyName: "Bajaj Housing Finance Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE377Y01014" },
  { symbol: "BAJAJHLDNG", companyName: "Bajaj Holdings & Investment Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE118A01012" },
  { symbol: "BAJFINANCE", companyName: "Bajaj Finance Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE296A01032" },
  { symbol: "BALKRISIND", companyName: "Balkrishna Industries Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE787D01026" },
  { symbol: "BANKBARODA", companyName: "Bank of Baroda", sector: "Financial Services", instrumentKey: "NSE_EQ|INE028A01039" },
  { symbol: "BANKINDIA", companyName: "Bank of India", sector: "Financial Services", instrumentKey: "NSE_EQ|INE084A01016" },
  { symbol: "BDL", companyName: "Bharat Dynamics Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE171Z01026" },
  { symbol: "BEL", companyName: "Bharat Electronics Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE263A01024" },
  { symbol: "BERGEPAINT", companyName: "Berger Paints India Ltd", sector: "Consumer Durables", instrumentKey: "NSE_EQ|INE463A01038" },
  { symbol: "BHARATFORG", companyName: "Bharat Forge Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE465A01025" },
  { symbol: "BHARTIARTL", companyName: "Bharti Airtel Ltd", sector: "Telecommunication", instrumentKey: "NSE_EQ|INE397D01024" },
  { symbol: "BHARTIHEXA", companyName: "Bharti Hexacom Ltd", sector: "Telecommunication", instrumentKey: "NSE_EQ|INE343G01021" },
  { symbol: "BHEL", companyName: "Bharat Heavy Electricals Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE257A01026" },
  { symbol: "BIOCON", companyName: "Biocon Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE376G01013" },
  { symbol: "BLUESTARCO", companyName: "Blue Star Ltd", sector: "Consumer Durables", instrumentKey: "NSE_EQ|INE472A01039" },
  { symbol: "BOSCHLTD", companyName: "Bosch Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE323A01026" },
  { symbol: "BPCL", companyName: "Bharat Petroleum Corporation Ltd", sector: "Oil Gas & Consumable Fuels", instrumentKey: "NSE_EQ|INE029A01011" },
  { symbol: "BRITANNIA", companyName: "Britannia Industries Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE216A01030" },
  { symbol: "BSE", companyName: "BSE Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE118H01025" },
  { symbol: "CANBK", companyName: "Canara Bank", sector: "Financial Services", instrumentKey: "NSE_EQ|INE476A01022" },
  { symbol: "CGPOWER", companyName: "CG Power and Industrial Solutions Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE067A01029" },
  { symbol: "CHOLAFIN", companyName: "Cholamandalam Investment and Finance Company Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE121A01024" },
  { symbol: "CIPLA", companyName: "Cipla Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE059A01026" },
  { symbol: "COALINDIA", companyName: "Coal India Ltd", sector: "Oil Gas & Consumable Fuels", instrumentKey: "NSE_EQ|INE522F01014" },
  { symbol: "COCHINSHIP", companyName: "Cochin Shipyard Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE704P01025" },
  { symbol: "COFORGE", companyName: "Coforge Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE591G01025" },
  { symbol: "COLPAL", companyName: "Colgate Palmolive (India) Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE259A01022" },
  { symbol: "CONCOR", companyName: "Container Corporation of India Ltd", sector: "Services", instrumentKey: "NSE_EQ|INE111A01025" },
  { symbol: "COROMANDEL", companyName: "Coromandel International Ltd", sector: "Chemicals", instrumentKey: "NSE_EQ|INE169A01031" },
  { symbol: "CRISIL", companyName: "CRISIL Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE007A01025" },
  { symbol: "CUMMINSIND", companyName: "Cummins India Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE298A01020" },
  { symbol: "DABUR", companyName: "Dabur India Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE016A01026" },
  { symbol: "DALBHARAT", companyName: "Dalmia Bharat Ltd", sector: "Construction Materials", instrumentKey: "NSE_EQ|INE00R701025" },
  { symbol: "DIVISLAB", companyName: "Divi's Laboratories Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE361B01024" },
  { symbol: "DIXON", companyName: "Dixon Technologies (India) Ltd", sector: "Consumer Durables", instrumentKey: "NSE_EQ|INE935N01020" },
  { symbol: "DLF", companyName: "DLF Ltd", sector: "Realty", instrumentKey: "NSE_EQ|INE271C01023" },
  { symbol: "DMART", companyName: "Avenue Supermarts Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE192R01011" },
  { symbol: "DRREDDY", companyName: "Dr. Reddy's Laboratories Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE089A01031" },
  { symbol: "EICHERMOT", companyName: "Eicher Motors Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE066A01021" },
  { symbol: "ENDURANCE", companyName: "Endurance Technologies Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE913H01037" },
  { symbol: "ENRIN", companyName: "Siemens Energy India Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE1NPP01017" },
  { symbol: "ESCORTS", companyName: "Escorts Kubota Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE042A01014" },
  { symbol: "ETERNAL", companyName: "Eternal Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE758T01015" },
  { symbol: "EXIDEIND", companyName: "Exide Industries Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE302A01020" },
  { symbol: "FEDERALBNK", companyName: "Federal Bank Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE171A01029" },
  { symbol: "FLUOROCHEM", companyName: "Gujarat Fluorochemicals Ltd", sector: "Chemicals", instrumentKey: "NSE_EQ|INE09N301011" },
  { symbol: "FORTIS", companyName: "Fortis Healthcare Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE061F01013" },
  { symbol: "GAIL", companyName: "GAIL (India) Ltd", sector: "Oil Gas & Consumable Fuels", instrumentKey: "NSE_EQ|INE129A01019" },
  { symbol: "GICRE", companyName: "General Insurance Corporation of India", sector: "Financial Services", instrumentKey: "NSE_EQ|INE481Y01014" },
  { symbol: "GLAXO", companyName: "Glaxosmithkline Pharmaceuticals Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE159A01016" },
  { symbol: "GLENMARK", companyName: "Glenmark Pharmaceuticals Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE935A01035" },
  { symbol: "GMRAIRPORT", companyName: "GMR Airports Ltd", sector: "Services", instrumentKey: "NSE_EQ|INE776C01039" },
  { symbol: "GODFRYPHLP", companyName: "Godfrey Phillips India Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE260B01028" },
  { symbol: "GODREJCP", companyName: "Godrej Consumer Products Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE102D01028" },
  { symbol: "GODREJIND", companyName: "Godrej Industries Ltd", sector: "Diversified", instrumentKey: "NSE_EQ|INE233A01035" },
  { symbol: "GODREJPROP", companyName: "Godrej Properties Ltd", sector: "Realty", instrumentKey: "NSE_EQ|INE484J01027" },
  { symbol: "GRASIM", companyName: "Grasim Industries Ltd", sector: "Construction Materials", instrumentKey: "NSE_EQ|INE047A01021" },
  { symbol: "GROWW", companyName: "Billionbrains Garage Ventures Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE0HOQ01053" },
  { symbol: "GVT&D", companyName: "GE Vernova T&D India Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE200A01026" },
  { symbol: "HAL", companyName: "Hindustan Aeronautics Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE066F01020" },
  { symbol: "HAVELLS", companyName: "Havells India Ltd", sector: "Consumer Durables", instrumentKey: "NSE_EQ|INE176B01034" },
  { symbol: "HCLTECH", companyName: "HCL Technologies Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE860A01027" },
  { symbol: "HDBFS", companyName: "HDB Financial Services Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE756I01012" },
  { symbol: "HDFCAMC", companyName: "HDFC Asset Management Company Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE127D01025" },
  { symbol: "HDFCBANK", companyName: "HDFC Bank Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE040A01034" },
  { symbol: "HDFCLIFE", companyName: "HDFC Life Insurance Company Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE795G01014" },
  { symbol: "HEROMOTOCO", companyName: "Hero MotoCorp Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE158A01026" },
  { symbol: "HEXT", companyName: "Hexaware Technologies Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE093A01041" },
  { symbol: "HINDALCO", companyName: "Hindalco Industries Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE038A01020" },
  { symbol: "HINDPETRO", companyName: "Hindustan Petroleum Corporation Ltd", sector: "Oil Gas & Consumable Fuels", instrumentKey: "NSE_EQ|INE094A01015" },
  { symbol: "HINDUNILVR", companyName: "Hindustan Unilever Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE030A01027" },
  { symbol: "HINDZINC", companyName: "Hindustan Zinc Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE267A01025" },
  { symbol: "HONAUT", companyName: "Honeywell Automation India Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE671A01010" },
  { symbol: "HUDCO", companyName: "Housing & Urban Development Corporation Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE031A01017" },
  { symbol: "HYUNDAI", companyName: "Hyundai Motor India Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE0V6F01027" },
  { symbol: "ICICIAMC", companyName: "ICICI Prudential Asset Management Company Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE346A01027" },
  { symbol: "ICICIBANK", companyName: "ICICI Bank Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE090A01021" },
  { symbol: "ICICIGI", companyName: "ICICI Lombard General Insurance Company Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE765G01017" },
  { symbol: "ICICIPRULI", companyName: "ICICI Prudential Life Insurance Company Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE726G01019" },
  { symbol: "IDEA", companyName: "Vodafone Idea Ltd", sector: "Telecommunication", instrumentKey: "NSE_EQ|INE669E01016" },
  { symbol: "IDFCFIRSTB", companyName: "IDFC First Bank Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE092T01019" },
  { symbol: "INDHOTEL", companyName: "Indian Hotels Co. Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE053A01029" },
  { symbol: "INDIANB", companyName: "Indian Bank", sector: "Financial Services", instrumentKey: "NSE_EQ|INE562A01011" },
  { symbol: "INDIGO", companyName: "InterGlobe Aviation Ltd", sector: "Services", instrumentKey: "NSE_EQ|INE646L01027" },
  { symbol: "INDUSINDBK", companyName: "IndusInd Bank Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE095A01012" },
  { symbol: "INDUSTOWER", companyName: "Indus Towers Ltd", sector: "Telecommunication", instrumentKey: "NSE_EQ|INE121J01017" },
  { symbol: "INFY", companyName: "Infosys Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE009A01021" },
  { symbol: "IOC", companyName: "Indian Oil Corporation Ltd", sector: "Oil Gas & Consumable Fuels", instrumentKey: "NSE_EQ|INE242A01010" },
  { symbol: "IPCALAB", companyName: "Ipca Laboratories Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE571A01038" },
  { symbol: "IRCTC", companyName: "Indian Railway Catering And Tourism Corporation Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE335Y01020" },
  { symbol: "IREDA", companyName: "Indian Renewable Energy Development Agency Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE202E01016" },
  { symbol: "IRFC", companyName: "Indian Railway Finance Corporation Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE053F01010" },
  { symbol: "ITC", companyName: "ITC Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE154A01025" },
  { symbol: "ITCHOTELS", companyName: "ITC Hotels Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE379A01028" },
  { symbol: "JINDALSTEL", companyName: "Jindal Steel Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE749A01030" },
  { symbol: "JIOFIN", companyName: "Jio Financial Services Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE758E01017" },
  { symbol: "JKCEMENT", companyName: "J.K. Cement Ltd", sector: "Construction Materials", instrumentKey: "NSE_EQ|INE823G01014" },
  { symbol: "JSL", companyName: "Jindal Stainless Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE220G01021" },
  { symbol: "JSWENERGY", companyName: "JSW Energy Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE121E01018" },
  { symbol: "JSWINFRA", companyName: "JSW Infrastructure Ltd", sector: "Services", instrumentKey: "NSE_EQ|INE880J01026" },
  { symbol: "JSWSTEEL", companyName: "JSW Steel Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE019A01038" },
  { symbol: "JUBLFOOD", companyName: "Jubilant Foodworks Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE797F01020" },
  { symbol: "KALYANKJIL", companyName: "Kalyan Jewellers India Ltd", sector: "Consumer Durables", instrumentKey: "NSE_EQ|INE303R01014" },
  { symbol: "KEI", companyName: "KEI Industries Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE878B01027" },
  { symbol: "KOTAKBANK", companyName: "Kotak Mahindra Bank Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE237A01036" },
  { symbol: "KPITTECH", companyName: "KPIT Technologies Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE04I401011" },
  { symbol: "KPRMILL", companyName: "K.P.R. Mill Ltd", sector: "Textiles", instrumentKey: "NSE_EQ|INE930H01031" },
  { symbol: "LAURUSLABS", companyName: "Laurus Labs Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE947Q01028" },
  { symbol: "LENSKART", companyName: "Lenskart Solutions Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE956O01016" },
  { symbol: "LGEINDIA", companyName: "LG Electronics India Ltd", sector: "Consumer Durables", instrumentKey: "NSE_EQ|INE324D01010" },
  { symbol: "LICHSGFIN", companyName: "LIC Housing Finance Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE115A01026" },
  { symbol: "LICI", companyName: "Life Insurance Corporation of India", sector: "Financial Services", instrumentKey: "NSE_EQ|INE0J1Y01017" },
  { symbol: "LINDEINDIA", companyName: "Linde India Ltd", sector: "Chemicals", instrumentKey: "NSE_EQ|INE473A01011" },
  { symbol: "LLOYDSME", companyName: "Lloyds Metals And Energy Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE281B01032" },
  { symbol: "LODHA", companyName: "Lodha Developers Ltd", sector: "Realty", instrumentKey: "NSE_EQ|INE670K01029" },
  { symbol: "LT", companyName: "Larsen & Toubro Ltd", sector: "Construction", instrumentKey: "NSE_EQ|INE018A01030" },
  { symbol: "LTF", companyName: "L&T Finance Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE498L01015" },
  { symbol: "LTM", companyName: "LTM Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE214T01019" },
  { symbol: "LTTS", companyName: "L&T Technology Services Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE010V01017" },
  { symbol: "LUPIN", companyName: "Lupin Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE326A01037" },
  { symbol: "M&M", companyName: "Mahindra & Mahindra Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE101A01026" },
  { symbol: "M&MFIN", companyName: "Mahindra & Mahindra Financial Services Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE774D01024" },
  { symbol: "MAHABANK", companyName: "Bank of Maharashtra", sector: "Financial Services", instrumentKey: "NSE_EQ|INE457A01014" },
  { symbol: "MANKIND", companyName: "Mankind Pharma Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE634S01028" },
  { symbol: "MARICO", companyName: "Marico Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE196A01026" },
  { symbol: "MARUTI", companyName: "Maruti Suzuki India Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE585B01010" },
  { symbol: "MAXHEALTH", companyName: "Max Healthcare Institute Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE027H01010" },
  { symbol: "MAZDOCK", companyName: "Mazagoan Dock Shipbuilders Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE249Z01020" },
  { symbol: "MCX", companyName: "Multi Commodity Exchange of India Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE745G01043" },
  { symbol: "MEDANTA", companyName: "Global Health Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE474Q01031" },
  { symbol: "MFSL", companyName: "Max Financial Services Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE180A01020" },
  { symbol: "MOTHERSON", companyName: "Samvardhana Motherson International Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE775A01035" },
  { symbol: "MOTILALOFS", companyName: "Motilal Oswal Financial Services Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE338I01027" },
  { symbol: "MPHASIS", companyName: "MphasiS Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE356A01018" },
  { symbol: "MRF", companyName: "MRF Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE883A01011" },
  { symbol: "MUTHOOTFIN", companyName: "Muthoot Finance Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE414G01012" },
  { symbol: "NAM-INDIA", companyName: "Nippon Life India Asset Management Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE298J01013" },
  { symbol: "NATIONALUM", companyName: "National Aluminium Co. Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE139A01034" },
  { symbol: "NAUKRI", companyName: "Info Edge (India) Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE663F01032" },
  { symbol: "NESTLEIND", companyName: "Nestle India Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE239A01024" },
  { symbol: "NHPC", companyName: "NHPC Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE848E01016" },
  { symbol: "NIACL", companyName: "The New India Assurance Company Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE470Y01017" },
  { symbol: "NLCINDIA", companyName: "NLC India Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE589A01014" },
  { symbol: "NMDC", companyName: "NMDC Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE584A01023" },
  { symbol: "NTPC", companyName: "NTPC Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE733E01010" },
  { symbol: "NTPCGREEN", companyName: "NTPC Green Energy Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE0ONG01011" },
  { symbol: "NYKAA", companyName: "FSN E-Commerce Ventures Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE388Y01029" },
  { symbol: "OBEROIRLTY", companyName: "Oberoi Realty Ltd", sector: "Realty", instrumentKey: "NSE_EQ|INE093I01010" },
  { symbol: "OFSS", companyName: "Oracle Financial Services Software Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE881D01027" },
  { symbol: "OIL", companyName: "Oil India Ltd", sector: "Oil Gas & Consumable Fuels", instrumentKey: "NSE_EQ|INE274J01014" },
  { symbol: "ONGC", companyName: "Oil & Natural Gas Corporation Ltd", sector: "Oil Gas & Consumable Fuels", instrumentKey: "NSE_EQ|INE213A01029" },
  { symbol: "PAGEIND", companyName: "Page Industries Ltd", sector: "Textiles", instrumentKey: "NSE_EQ|INE761H01022" },
  { symbol: "PATANJALI", companyName: "Patanjali Foods Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE619A01035" },
  { symbol: "PAYTM", companyName: "One 97 Communications Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE982J01020" },
  { symbol: "PERSISTENT", companyName: "Persistent Systems Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE262H01021" },
  { symbol: "PETRONET", companyName: "Petronet LNG Ltd", sector: "Oil Gas & Consumable Fuels", instrumentKey: "NSE_EQ|INE347G01014" },
  { symbol: "PFC", companyName: "Power Finance Corporation Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE134E01011" },
  { symbol: "PHOENIXLTD", companyName: "Phoenix Mills Ltd", sector: "Realty", instrumentKey: "NSE_EQ|INE211B01039" },
  { symbol: "PIDILITIND", companyName: "Pidilite Industries Ltd", sector: "Chemicals", instrumentKey: "NSE_EQ|INE318A01026" },
  { symbol: "PIIND", companyName: "PI Industries Ltd", sector: "Chemicals", instrumentKey: "NSE_EQ|INE603J01030" },
  { symbol: "PNB", companyName: "Punjab National Bank", sector: "Financial Services", instrumentKey: "NSE_EQ|INE160A01022" },
  { symbol: "POLICYBZR", companyName: "PB Fintech Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE417T01026" },
  { symbol: "POLYCAB", companyName: "Polycab India Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE455K01017" },
  { symbol: "POWERGRID", companyName: "Power Grid Corporation of India Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE752E01010" },
  { symbol: "POWERINDIA", companyName: "Hitachi Energy India Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE07Y701011" },
  { symbol: "PREMIERENE", companyName: "Premier Energies Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE0BS701011" },
  { symbol: "PRESTIGE", companyName: "Prestige Estates Projects Ltd", sector: "Realty", instrumentKey: "NSE_EQ|INE811K01011" },
  { symbol: "RADICO", companyName: "Radico Khaitan Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE944F01028" },
  { symbol: "RECLTD", companyName: "REC Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE020B01018" },
  { symbol: "RELIANCE", companyName: "Reliance Industries Ltd", sector: "Oil Gas & Consumable Fuels", instrumentKey: "NSE_EQ|INE002A01018" },
  { symbol: "RVNL", companyName: "Rail Vikas Nigam Ltd", sector: "Construction", instrumentKey: "NSE_EQ|INE415G01027" },
  { symbol: "SAIL", companyName: "Steel Authority of India Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE114A01011" },
  { symbol: "SBICARD", companyName: "SBI Cards and Payment Services Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE018E01016" },
  { symbol: "SBILIFE", companyName: "SBI Life Insurance Company Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE123W01016" },
  { symbol: "SBIN", companyName: "State Bank of India", sector: "Financial Services", instrumentKey: "NSE_EQ|INE062A01020" },
  { symbol: "SCHAEFFLER", companyName: "Schaeffler India Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE513A01022" },
  { symbol: "SHREECEM", companyName: "Shree Cement Ltd", sector: "Construction Materials", instrumentKey: "NSE_EQ|INE070A01015" },
  { symbol: "SHRIRAMFIN", companyName: "Shriram Finance Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE721A01047" },
  { symbol: "SIEMENS", companyName: "Siemens Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE003A01024" },
  { symbol: "SJVN", companyName: "SJVN Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE002L01015" },
  { symbol: "SOLARINDS", companyName: "Solar Industries India Ltd", sector: "Chemicals", instrumentKey: "NSE_EQ|INE343H01029" },
  { symbol: "SRF", companyName: "SRF Ltd", sector: "Chemicals", instrumentKey: "NSE_EQ|INE647A01010" },
  { symbol: "SUNDARMFIN", companyName: "Sundaram Finance Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE660A01013" },
  { symbol: "SUNPHARMA", companyName: "Sun Pharmaceutical Industries Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE044A01036" },
  { symbol: "SUPREMEIND", companyName: "Supreme Industries Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE195A01028" },
  { symbol: "SUZLON", companyName: "Suzlon Energy Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE040H01021" },
  { symbol: "SWIGGY", companyName: "Swiggy Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE00H001014" },
  { symbol: "TATACAP", companyName: "Tata Capital Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE976I01016" },
  { symbol: "TATACOMM", companyName: "Tata Communications Ltd", sector: "Telecommunication", instrumentKey: "NSE_EQ|INE151A01013" },
  { symbol: "TATACONSUM", companyName: "Tata Consumer Products Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE192A01025" },
  { symbol: "TATAELXSI", companyName: "Tata Elxsi Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE670A01012" },
  { symbol: "TATAINVEST", companyName: "Tata Investment Corporation Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE672A01026" },
  { symbol: "TATAPOWER", companyName: "Tata Power Co. Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE245A01021" },
  { symbol: "TATASTEEL", companyName: "Tata Steel Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE081A01020" },
  { symbol: "TCS", companyName: "Tata Consultancy Services Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE467B01029" },
  { symbol: "TECHM", companyName: "Tech Mahindra Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE669C01036" },
  { symbol: "THERMAX", companyName: "Thermax Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE152A01029" },
  { symbol: "TIINDIA", companyName: "Tube Investments of India Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE974X01010" },
  { symbol: "TITAN", companyName: "Titan Company Ltd", sector: "Consumer Durables", instrumentKey: "NSE_EQ|INE280A01028" },
  { symbol: "TMCV", companyName: "Tata Motors Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE1TAE01010" },
  { symbol: "TMPV", companyName: "Tata Motors Passenger Vehicles Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE155A01022" },
  { symbol: "TORNTPHARM", companyName: "Torrent Pharmaceuticals Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE685A01028" },
  { symbol: "TORNTPOWER", companyName: "Torrent Power Ltd", sector: "Power", instrumentKey: "NSE_EQ|INE813H01021" },
  { symbol: "TRENT", companyName: "Trent Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE849A01020" },
  { symbol: "TVSMOTOR", companyName: "TVS Motor Company Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE494B01023" },
  { symbol: "UBL", companyName: "United Breweries Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE686F01025" },
  { symbol: "ULTRACEMCO", companyName: "UltraTech Cement Ltd", sector: "Construction Materials", instrumentKey: "NSE_EQ|INE481G01011" },
  { symbol: "UNIONBANK", companyName: "Union Bank of India", sector: "Financial Services", instrumentKey: "NSE_EQ|INE692A01016" },
  { symbol: "UNITDSPR", companyName: "United Spirits Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE854D01024" },
  { symbol: "UNOMINDA", companyName: "UNO Minda Ltd", sector: "Automobile and Auto Components", instrumentKey: "NSE_EQ|INE405E01023" },
  { symbol: "UPL", companyName: "UPL Ltd", sector: "Chemicals", instrumentKey: "NSE_EQ|INE628A01036" },
  { symbol: "VBL", companyName: "Varun Beverages Ltd", sector: "Fast Moving Consumer Goods", instrumentKey: "NSE_EQ|INE200M01039" },
  { symbol: "VEDL", companyName: "Vedanta Ltd", sector: "Metals & Mining", instrumentKey: "NSE_EQ|INE205A01025" },
  { symbol: "VMM", companyName: "Vishal Mega Mart Ltd", sector: "Consumer Services", instrumentKey: "NSE_EQ|INE01EA01019" },
  { symbol: "VOLTAS", companyName: "Voltas Ltd", sector: "Consumer Durables", instrumentKey: "NSE_EQ|INE226A01021" },
  { symbol: "WAAREEENER", companyName: "Waaree Energies Ltd", sector: "Capital Goods", instrumentKey: "NSE_EQ|INE377N01017" },
  { symbol: "WIPRO", companyName: "Wipro Ltd", sector: "Information Technology", instrumentKey: "NSE_EQ|INE075A01022" },
  { symbol: "YESBANK", companyName: "Yes Bank Ltd", sector: "Financial Services", instrumentKey: "NSE_EQ|INE528G01035" },
  { symbol: "ZYDUSLIFE", companyName: "Zydus Lifesciences Ltd", sector: "Healthcare", instrumentKey: "NSE_EQ|INE010B01027" },
];

/** Real NSE sector/industry names present in the current universe, sorted alphabetically. */
export const SECTOR_NAMES: readonly string[] = Array.from(new Set(RTT2X_UNIVERSE.map((stock) => stock.sector))).sort();

const BY_SYMBOL = new Map(RTT2X_UNIVERSE.map((stock) => [stock.symbol, stock]));

export function findUniverseStock(symbol: string): UniverseStock | null {
  return BY_SYMBOL.get(symbol) ?? null;
}

/** Seam for a future live instrument-master lookup; currently backed by the static universe above. */
export function resolveInstrumentKey(symbol: string): string | null {
  return BY_SYMBOL.get(symbol)?.instrumentKey ?? null;
}
